title: Above It All
description: A website with a blog
footer_text: Copyright 2021 Lester John
header_feature_image: ../uploads/diana-macesanu-3cihxbx9h0u-unsplash.jpg
header_text: Above It All
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/logo.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
