title: Dungeons & Design
description: A website with a blog
footer_text: Copyright 2021 Lester John
header_feature_image: ../uploads/alberto-zanetti-x3esiiuz3fi-unsplash.jpg
header_text: Welcome To The Dungeon
header_text_color: "#eae7e7"
bannerheight: 40vmax
navbarheight: 55px
logo: ../uploads/dungeons.png
favicon: ../uploads/favicon.ico
gridlayout: true
fixednavbar: true
upzoom: true
items:
  - name: About The Author
    siteurl: /aboutme/
