title: Dungeons & Design
description: A website with a blog
footer_text: Copyright 2021 Lester John
header_feature_image: ""
header_text: Welcome To The Dungeon
header_text_color: "#eae7e7"
bannerheight: 40vmax
navbarheight: 55px
logo: ../uploads/logo.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
items:
  - name: About The Author
    siteurl: emergence/aboutme/
