title: Above It All
description: A website with a blog
footer_text: Copyright 2021 Lester John
header_feature_image: ../uploads/dji_0410.jpg
header_text: Above It All - Welcome Home
header_text_color: "#eae7e7"
bannerheight: 60vmax
navbarheight: 55px
logo: ../uploads/logo.png
favicon: /uploads/favicon.ico
gridlayout: true
fixednavbar: true
upzoom: true
